### ISSUE TITLE
Microverse Instruction

### ISSUE THREAD

**Issue by unorjikingsley** [lordksix/BooksApp-ES6#3]
Your project is so professional for a beginner like me. Also, it would be great to follow the microverse instruction for the project so others can understand your code better while you can have this as a personal repo. but great work. I love your code.

**Comment by lordksix** [comment]
@unorjikingsley Thank you for the word and truly appreciate the feedback. However, the project is within the scope and requirements asked about. The requirements were as follows:
- A completely modular with ES6 standards:
https://github.com/microverseinc/curriculum-javascript/blob/17555a4b0793b5065e3aeda6d2568fddd9c45330/books/books_with_es6.md?plain=1#L44-L50
- Use luxon after installing using npm:
https://github.com/microverseinc/curriculum-javascript/blob/17555a4b0793b5065e3aeda6d2568fddd9c45330/books/books_with_es6.md?plain=1#L53-L55
-However it is against ESM rules, you have an uncaught exception, so the solution found was with the program's day's lessons. 

Cheers,
@lordksix
